[package]
name = "bevy_2settings"
version = "0.0.0"
edition = "2024"

[dependencies]
bevy_2settings_macro = { path = "../bevy_2settings_macro" }
bevy = "0.16"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
